[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
flask = "*"
python = "^3.7"
[tool.poetry.dependencies."discord.py"]
extras = ["voice"]
version = "==1.2.0"
